#!/bin/sh
# gen_dist11.sh - regenerate tests/dist11.txt: every state at exact
# half-turn-metric distance 11 (2644 states), one 14-character solver input
# per line, LC_ALL=C sorted, after a 2-line '#' header.  Test data only.
#
# Usage:  sh tools/oracle/gen_dist11.sh [OUTPUT]     (from any directory)
#         sh tools/oracle/gen_dist11.sh -h           (print this usage)
#         make -C tools/oracle dist11                (same, default OUTPUT)
#   OUTPUT defaults to tests/dist11.txt in this repository.  It must be a
#   regular file or not exist yet, in an existing directory, and must not
#   start with '-' (write ./-name for such a file).
# Requires tools/oracle/oracle, built from the current oracle.c, oracle.h,
# oracle_cli.c and ../../solver.c (build: make -C tools/oracle); a binary
# older than any of them is refused.
# Prints a one-line summary.  Exit status: 0 success; 1 failed assertion,
# missing or stale oracle, or I/O error (any existing OUTPUT is left
# untouched); 2 usage error (bad option, extra argument, bad OUTPUT).
set -eu

UPSTREAM_COMMIT=231796cc48868f4ea276f652139b6bebbad0cd02
EXPECTED=2644
SAMPLE=21345671111111

die() {
    printf 'gen_dist11.sh: %s\n' "$*" >&2
    exit 1
}

usage() {
    echo "usage: sh gen_dist11.sh [OUTPUT]   (default OUTPUT: <repo>/tests/dist11.txt)"
}

bad_usage() {
    printf 'gen_dist11.sh: %s\n' "$*" >&2
    usage >&2
    exit 2
}

case $# in
0) ;;
1)
    case "$1" in
    -h | --help) usage; exit 0 ;;
    '') bad_usage "OUTPUT must not be empty" ;;
    -*) bad_usage "unknown option '$1' (write ./$1 for a file of that name)" ;;
    esac
    ;;
*) bad_usage "expected at most one argument, got $#" ;;
esac

here=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd) || die "cannot locate script"
root=$(CDPATH='' cd -- "$here/../.." && pwd) || die "cannot locate repository"
oracle="$here/oracle"
out="${1:-$root/tests/dist11.txt}"
outdir=$(dirname -- "$out")

[ -d "$outdir" ] || bad_usage "output directory $outdir does not exist"
[ ! -d "$out" ] || bad_usage "OUTPUT $out is a directory; give a file path"
[ ! -e "$out" ] || [ -f "$out" ] ||
    bad_usage "OUTPUT $out exists and is not a regular file"
[ -x "$oracle" ] || die "missing $oracle; build it first: make -C \"$here\""
# Refuse a binary older than its sources (POSIX find -newer).
stale=$(find "$here/oracle.c" "$here/oracle.h" "$here/oracle_cli.c" \
    "$root/solver.c" -newer "$oracle" -print) || die "cannot stat oracle sources"
[ -z "$stale" ] ||
    die "$oracle is older than $(printf '%s\n' "$stale" | paste -s -d ' ' -); rebuild: make -C \"$here\""

# The header names the upstream commit, so insist solver.c is that blob.
if command -v git >/dev/null 2>&1 &&
    git -C "$root" rev-parse --git-dir >/dev/null 2>&1; then
    want=$(git -C "$root" rev-parse "$UPSTREAM_COMMIT:solver.c" 2>/dev/null) ||
        die "upstream commit $UPSTREAM_COMMIT is not in this repository"
    have=$(git -C "$root" hash-object "$root/solver.c") ||
        die "git hash-object solver.c failed"
    [ "$want" = "$have" ] ||
        die "solver.c differs from upstream $UPSTREAM_COMMIT; refusing to label output"
else
    printf 'gen_dist11.sh: warning: no git; cannot confirm solver.c is %s\n' \
        "$UPSTREAM_COMMIT" >&2
fi

tmp=$(mktemp "$outdir/.dist11.XXXXXX") || die "mktemp failed in $outdir"
trap 'rm -f "$tmp" "$tmp.raw" "$tmp.body" "$tmp.dist"' 0
trap 'exit 1' 1 2 15

"$oracle" list 11 >"$tmp.raw" || die "oracle list 11 failed"
LC_ALL=C sort "$tmp.raw" >"$tmp.body" || die "sort failed"

count=$(wc -l <"$tmp.body")
count=$((count + 0))
[ "$count" -eq "$EXPECTED" ] || die "expected $EXPECTED states, got $count"

LC_ALL=C awk '
    !/^[1-7][1-7][1-7][1-7][1-7][1-7][1-7][1-3][1-3][1-3][1-3][1-3][1-3][1-3]$/ {
        printf "gen_dist11.sh: malformed line %d: %s\n", NR, $0 > "/dev/stderr"
        bad = 1
    }
    END { exit bad }' "$tmp.body" || die "malformed state strings"

unique=$(LC_ALL=C sort -u "$tmp.body" | wc -l)
[ $((unique + 0)) -eq "$count" ] || die "duplicate states in list"
cmp -s "$tmp.raw" "$tmp.body" ||
    die "oracle rank order differs from LC_ALL=C sorted order"
grep -qx "$SAMPLE" "$tmp.body" || die "sample state $SAMPLE missing"

# Re-derive each distance through the string interface.
"$oracle" dist - <"$tmp.body" >"$tmp.dist" || die "oracle dist - failed"
awk -v want="$EXPECTED" '
    $2 != 11 { printf "gen_dist11.sh: %s has distance %s\n", $1, $2 > "/dev/stderr"; bad = 1 }
    END { if (NR != want) bad = 1; exit bad }' "$tmp.dist" ||
    die "oracle dist disagrees with oracle list"

{
    printf '# All %d states at exact HTM distance 11, one solver input per line, LC_ALL=C sorted.\n' "$count"
    printf '# Generated by: sh tools/oracle/gen_dist11.sh (tools/oracle/oracle list 11 | LC_ALL=C sort; BFS of unmodified solver.c, sysprog21/minirubik %s)\n' "$UPSTREAM_COMMIT"
    cat "$tmp.body"
} >"$tmp" || die "cannot write $tmp"
chmod 644 "$tmp"
mv -f "$tmp" "$out" || die "cannot replace $out"
printf 'gen_dist11.sh: wrote %s (%d states, includes %s)\n' "$out" "$count" "$SAMPLE"
