/* gen_tables.c - written with AI assistance (Claude Code); see docs/ai-assistance.md */
/*
 * Table emitter.  Builds the tables with tables_build() and writes them as
 *   --h FILE    C header with const initializers (c/tables_data.h), used by
 *               the host programs (via tables_embed.c) and the freestanding
 *               RV32I reference build (via ripes_ref.c);
 *   --asm FILE  Ripes-assembler data (asm/tables.s): one .data section with
 *               ".align 2", then labels perm_qt, orient_qt (.half) and
 *               pdb_p, pdb_o (.byte).
 * Usage: gen_tables [--h FILE] [--asm FILE]   (at least one option)
 * Exit status: 0 ok, 1 build or write error, 2 usage error.
 */
#include <stdio.h>
#include <string.h>

#include "tables.h"

#define PER_LINE 16

static const char *const face_names[TB_FACES] = {"R", "B", "D"};

static unsigned max_u8(const uint8_t *a, unsigned n)
{
    unsigned m = 0;
    for (unsigned i = 0; i < n; ++i)
        if (a[i] > m)
            m = a[i];
    return m;
}

/* Write n values as C initializer lines of PER_LINE values. */
static void c_values16(FILE *f, const uint16_t *a, unsigned n)
{
    for (unsigned i = 0; i < n; ++i)
        fprintf(f, "%s%u,%s", i % PER_LINE == 0 ? "        " : " ",
                (unsigned) a[i],
                (i % PER_LINE == PER_LINE - 1 || i == n - 1) ? "\n" : "");
}

static void c_values8(FILE *f, const uint8_t *a, unsigned n)
{
    for (unsigned i = 0; i < n; ++i)
        fprintf(f, "%s%u,%s", i % PER_LINE == 0 ? "    " : " ",
                (unsigned) a[i],
                (i % PER_LINE == PER_LINE - 1 || i == n - 1) ? "\n" : "");
}

static int write_header(const char *path)
{
    FILE *f = fopen(path, "w");
    if (!f) {
        perror(path);
        return 1;
    }
    fprintf(f,
            "/* tables_data.h - generated by c/gen_tables, do not edit "
            "(generator written with\n"
            "   AI assistance (Claude Code); see docs/ai-assistance.md). */\n"
            "/*\n"
            " * Read-only IDA* tables, generated on the host from upstream "
            "solver.c.\n"
            " *   perm_qt   uint16_t [3][5040]  %6u bytes\n"
            " *   orient_qt uint16_t [3][729]   %6u bytes\n"
            " *   pdb_p     uint8_t  [5040]     %6u bytes  (max %u)\n"
            " *   pdb_o     uint8_t  [729]      %6u bytes  (max %u)\n"
            " *   total                         %6u bytes\n"
            " * Face order R, B, D.  perm_qt[f][r] / orient_qt[f][r] = rank "
            "after one\n"
            " * quarter turn of face f (upstream quarter_turn(), i.e. move "
            "3*f).\n"
            " * Include in exactly one translation unit.\n"
            " */\n"
            "#ifndef MINIRUBIK_TABLES_DATA_H\n"
            "#define MINIRUBIK_TABLES_DATA_H\n\n"
            "#include <stdint.h>\n\n",
            (unsigned) sizeof gen_perm_qt, (unsigned) sizeof gen_orient_qt,
            (unsigned) sizeof gen_pdb_p, max_u8(gen_pdb_p, TB_PERMS),
            (unsigned) sizeof gen_pdb_o, max_u8(gen_pdb_o, TB_ORIENTS),
            (unsigned) (sizeof gen_perm_qt + sizeof gen_orient_qt +
                        sizeof gen_pdb_p + sizeof gen_pdb_o));

    fprintf(f, "const uint16_t perm_qt[3][5040] = {\n");
    for (unsigned face = 0; face < TB_FACES; ++face) {
        fprintf(f, "    { /* face %u (%s) */\n", face, face_names[face]);
        c_values16(f, gen_perm_qt[face], TB_PERMS);
        fprintf(f, "    },\n");
    }
    fprintf(f, "};\n\n");

    fprintf(f, "const uint16_t orient_qt[3][729] = {\n");
    for (unsigned face = 0; face < TB_FACES; ++face) {
        fprintf(f, "    { /* face %u (%s) */\n", face, face_names[face]);
        c_values16(f, gen_orient_qt[face], TB_ORIENTS);
        fprintf(f, "    },\n");
    }
    fprintf(f, "};\n\n");

    fprintf(f, "const uint8_t pdb_p[5040] = {\n");
    c_values8(f, gen_pdb_p, TB_PERMS);
    fprintf(f, "};\n\n");

    fprintf(f, "const uint8_t pdb_o[729] = {\n");
    c_values8(f, gen_pdb_o, TB_ORIENTS);
    fprintf(f, "};\n\n#endif /* MINIRUBIK_TABLES_DATA_H */\n");

    if (fflush(f) != 0 || ferror(f)) {
        perror(path);
        fclose(f);
        return 1;
    }
    return fclose(f) != 0;
}

/* One assembler directive line per PER_LINE values. */
static void asm_values(FILE *f, const char *directive, const void *data,
                       unsigned n, int wide)
{
    for (unsigned i = 0; i < n; ++i) {
        unsigned v = wide ? ((const uint16_t *) data)[i]
                          : ((const uint8_t *) data)[i];
        if (i % PER_LINE == 0)
            fprintf(f, "        %s %u", directive, v);
        else
            fprintf(f, ", %u", v);
        if (i % PER_LINE == PER_LINE - 1 || i == n - 1)
            fputc('\n', f);
    }
}

static int write_asm(const char *path)
{
    unsigned off_perm = 0;
    unsigned off_orient = off_perm + (unsigned) sizeof gen_perm_qt;
    unsigned off_pdb_p = off_orient + (unsigned) sizeof gen_orient_qt;
    unsigned off_pdb_o = off_pdb_p + (unsigned) sizeof gen_pdb_p;
    unsigned total = off_pdb_o + (unsigned) sizeof gen_pdb_o;
    FILE *f = fopen(path, "w");
    if (!f) {
        perror(path);
        return 1;
    }
    fprintf(f,
            "# tables.s - generated by c/gen_tables, do not edit.\n"
            "# (Generator written with AI assistance (Claude Code); see "
            "docs/ai-assistance.md.)\n"
            "# Read-only IDA* tables generated on the host from upstream "
            "solver.c\n"
            "# (precomputation rule). Ripes has no .include: append this "
            "file to the\n"
            "# program source. Only .data/.align/.half/.byte are used "
            "(Ripes has no\n"
            "# .rodata).\n"
            "#\n"
            "#   label      type    shape      bytes  offset  row stride\n"
            "#   perm_qt    .half   [3][5040]  %5u  %6u  10080 bytes "
            "(5040*2)\n"
            "#   orient_qt  .half   [3][729]   %5u  %6u   1458 bytes "
            "(729*2)\n"
            "#   pdb_p      .byte   [5040]     %5u  %6u  max %u\n"
            "#   pdb_o      .byte   [729]      %5u  %6u  max %u\n"
            "#   total                         %5u bytes (ends at an odd "
            "offset)\n"
            "#\n"
            "# Offsets are from perm_qt. In this Ripes build \".align N\" "
            "pads to a multiple\n"
            "# of N bytes (GNU as: 2^N bytes), so \".align 2\" below makes "
            "perm_qt and\n"
            "# orient_qt halfword aligned under both even when odd-length "
            "data comes\n"
            "# first. Data placed after pdb_o needs its own \".align 2\" "
            "(.half) or\n"
            "# \".align 4\" (.word).\n"
            "#\n"
            "# Rows are faces R=0, B=1, D=2. perm_qt[f][r] (orient_qt[f][r]) "
            "is the\n"
            "# p_rank (o_rank) after one quarter turn of face f (upstream "
            "quarter_turn,\n"
            "# i.e. move 3*f: R, B or D); pdb_p[p]\n"
            "# (pdb_o[o]) is the exact distance of p (o) in the "
            "permutation-only\n"
            "# (orientation-only) abstraction.\n"
            "\n"
            "        .data\n"
            "        .align 2\n",
            (unsigned) sizeof gen_perm_qt, off_perm,
            (unsigned) sizeof gen_orient_qt, off_orient,
            (unsigned) sizeof gen_pdb_p, off_pdb_p,
            max_u8(gen_pdb_p, TB_PERMS), (unsigned) sizeof gen_pdb_o,
            off_pdb_o, max_u8(gen_pdb_o, TB_ORIENTS), total);

    fprintf(f, "perm_qt:\n");
    for (unsigned face = 0; face < TB_FACES; ++face) {
        fprintf(f, "# perm_qt face %u (%s), offset %u\n", face,
                face_names[face], off_perm + face * TB_PERMS * 2u);
        asm_values(f, ".half", gen_perm_qt[face], TB_PERMS, 1);
    }
    fprintf(f, "orient_qt:\n");
    for (unsigned face = 0; face < TB_FACES; ++face) {
        fprintf(f, "# orient_qt face %u (%s), offset %u\n", face,
                face_names[face], off_orient + face * TB_ORIENTS * 2u);
        asm_values(f, ".half", gen_orient_qt[face], TB_ORIENTS, 1);
    }
    fprintf(f, "pdb_p:\n");
    asm_values(f, ".byte", gen_pdb_p, TB_PERMS, 0);
    fprintf(f, "pdb_o:\n");
    asm_values(f, ".byte", gen_pdb_o, TB_ORIENTS, 0);

    if (fflush(f) != 0 || ferror(f)) {
        perror(path);
        fclose(f);
        return 1;
    }
    return fclose(f) != 0;
}

static int usage(const char *argv0)
{
    fprintf(stderr, "usage: %s [--h FILE] [--asm FILE]\n",
            argv0 ? argv0 : "gen_tables");
    return 2;
}

int main(int argc, char **argv)
{
    const char *h_path = NULL, *asm_path = NULL;
    for (int i = 1; i < argc; ++i) {
        if (!strcmp(argv[i], "--h") && i + 1 < argc)
            h_path = argv[++i];
        else if (!strcmp(argv[i], "--asm") && i + 1 < argc)
            asm_path = argv[++i];
        else
            return usage(argv[0]);
    }
    if (!h_path && !asm_path)
        return usage(argc > 0 ? argv[0] : NULL);
    if (tables_build()) {
        fputs("gen_tables: a pattern database BFS left entries unreached\n",
              stderr);
        return 1;
    }
    if (h_path && write_header(h_path))
        return 1;
    if (asm_path && write_asm(asm_path))
        return 1;
    return 0;
}
