/* ida_core.h - written with AI assistance (Claude Code); see docs/ai-assistance.md */
/*
 * IDA* search core for the 2x2x2 cube (half-turn metric), C reference for
 * the RV32I port.  Freestanding: needs only <stdint.h>, no libc, no heap,
 * no recursion.  The read-only tables are declared extern here and defined
 * elsewhere (c/tables_data.h, generated by c/gen_tables), so the same core
 * links on the host and in the freestanding RV32I reference build.
 *
 * State = (p_rank, o_rank) with p_rank in 0..5039 and o_rank in 0..728,
 * ranked exactly like upstream rank_state() (rank = p_rank * 729 + o_rank).
 * Moves are numbered as upstream: 0..8 = R R2 R' B B2 B' D D2 D'
 * (move = 3 * face + turn, face 0..2 = R B D, turn 0..2 = 1..3 quarter turns).
 */
#ifndef MINIRUBIK_IDA_CORE_H
#define MINIRUBIK_IDA_CORE_H

#include <stdint.h>

#define IDA_FACES 3        /* R, B, D */
#define IDA_MOVES 9        /* 3 faces x 3 turns */
#define IDA_PERMS 5040     /* 7! */
#define IDA_ORIENTS 729    /* 3^6 */
#define IDA_MAX_DEPTH 11   /* HTM diameter (host result, gate H3) */
#define IDA_LEVELS (IDA_MAX_DEPTH + 1) /* search levels 0..11 */
#define IDA_FAIL (-1)      /* ida_solve: no solution within IDA_MAX_DEPTH */

/* Quarter-turn transition tables (row-major [face][rank]). */
extern const uint16_t perm_qt[IDA_FACES][IDA_PERMS];
extern const uint16_t orient_qt[IDA_FACES][IDA_ORIENTS];
/* Pattern databases: exact distance in each abstraction, one byte per entry. */
extern const uint8_t pdb_p[IDA_PERMS];
extern const uint8_t pdb_o[IDA_ORIENTS];

#ifdef IDA_STATS
/* Statistics, compiled only with -DIDA_STATS (host builds).  Reset by
 * ida_solve().  expanded: nodes whose children were generated (the root
 * once per bound iteration plus every node the search descended into).
 * generated: child states computed (one perm_qt + one orient_qt lookup). */
extern uint32_t ida_expanded;
extern uint32_t ida_generated;
#endif

/*
 * Parse and validate a 14-character state string with the same rules as
 * upstream parse_state()/valid(): s[0..6] are distinct digits '1'..'7',
 * s[7..13] are digits '1'..'3' whose (digit - 1) sum is a multiple of 3,
 * and s[14] == '\0'.  Stops at the first bad byte, so it never reads past
 * the terminating NUL.  On success stores the ranks and returns 1; returns
 * 0 for an invalid string (outputs untouched).  No multiply by a
 * non-constant, no divide.
 */
int ida_parse(const char *s, uint32_t *p_rank, uint32_t *o_rank);

/* Apply one move (0..8) through the quarter-turn tables.  Returns 0 and
 * leaves the state unchanged if move > 8, else 1. */
int ida_apply_move(uint32_t *p_rank, uint32_t *o_rank, uint32_t move);

/* Apply len moves from path to (p_rank, o_rank); returns 1 iff every move
 * is in 0..8 and the result is the solved state (0, 0). */
int ida_apply_path(uint32_t p_rank, uint32_t o_rank, const uint8_t *path,
                   uint32_t len);

/*
 * IDA* with h = max(pdb_p[p], pdb_o[o]) and same-face pruning.  Writes the
 * solution (move numbers) to path[0..len-1] and returns len (0..11), or
 * IDA_FAIL if no solution of length <= IDA_MAX_DEPTH exists (cannot happen
 * for a valid state).  Ranks must be in range.  Not reentrant: the
 * explicit search stack is static data.
 */
int ida_solve(uint32_t p_rank, uint32_t o_rank, uint8_t path[IDA_MAX_DEPTH]);

#endif /* MINIRUBIK_IDA_CORE_H */
